version: '3.6'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy:1.0.1
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./docker-configs/nginx/my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf"

  nginx:
    image: nginx:1.23.1
    ports:
      - "127.0.0.1:8000:80"
    environment:
      - "VIRTUAL_HOST=parkovochka.work,api.parkovochka.work,admin.parkovochka.work"
    volumes:
      - "./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app:cached"
    depends_on:
      - "php"

  php:
    build: "./docker-configs/php"
    environment:
      - "PHP_IDE_CONFIG=serverName=parkovochka-backend-docker"
      - "SHELL=/bin/bash"
    volumes:
      - "./docker-configs/php/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini"
      - "./docker-configs/php/php-fpm.ini:/etc/php/8.2/fpm/php.ini"
      - "./docker-configs/php/php-cli.ini:/etc/php/8.2/cli/php.ini"
      - ".:/app:cached"
      - "composer:/var/www/.composer"
      - "bash-history-user:/var/www/history/"
      - "bash-history-root:/root/history/"
    depends_on:
      - "postgresql"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgresql:
    image: postgis/postgis:15-3.3
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_PASSWORD=qwerty"
      - "POSTGRES_DB=parkovochka-dev"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:15432:5432"

  pgadmin4:
    image: dpage/pgadmin4:6.12
    environment:
      PGADMIN_SERVER_NAME: postgresql
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - "127.0.0.1:6789:80"
    depends_on:
      - "postgresql"
    volumes:
      - "pgadmin4-data:/var/lib/pgadmin"

volumes:
  postgres-data:
  pgadmin4-data:
  composer:
  bash-history-user:
  bash-history-root:
