GET {{api_scheme}}{{api_host}}/api/{{api_version}}/parkings
Accept-Language: {{default_language}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
