admin:
    resource: ../src/Controller/Admin
    type: attribute
    host: "%admin_host%"
    schemes: "%admin_scheme%"

landing:
    resource: ../src/Controller/Landing
    type: attribute
    host: "%landing_host%"
    schemes: "%landing_scheme%"

api_v10:
    resource: ../src/Controller/API/V10
    type: attribute
    prefix: /api/v1.0
    host: "%api_host%"
    schemes: "%api_scheme%"