parameters:
    locale: 'uk'
    locales:
        - 'en'
        - 'uk'
    api_host: '%env(APP_API_HOST)%'
    api_scheme: '%env(APP_API_SCHEME)%'
    admin_host: '%env(APP_ADMIN_HOST)%'
    admin_scheme: '%env(APP_ADMIN_SCHEME)%'
    landing_host: '%env(APP_LANDING_HOST)%'
    landing_scheme: '%env(APP_LANDING_SCHEME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultLocale: '%locale%'
            $supportedLocales: '%locales%'
            $filesystem: '@oneup_flysystem.file_fs_filesystem'
    App\:
        resource: '../src/{DependencyInjection,EventListener,Repository,Request,Serializer,Service,Traits,Util,Validator}/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\File\UniqidLowercaseNamer:
        public: true
        tags:
            - { name: namer }

    App\DataFixtures\ORM\:
        resource: '../src/DataFixtures/ORM/'

    App\EventListener\ORM\DateTime\DateTimeInUTCListener:
        class: App\EventListener\ORM\DateTime\DateTimeInUTCListener
        tags:
            - { name: doctrine.event_listener, event: preFlush }

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer: '@serializer.normalizer.datetime'
    Symfony\Component\Serializer\Serializer: '@serializer'
    Doctrine\ORM\EntityManager: '@doctrine.orm.entity_manager'