POST {{api_scheme}}{{api_host}}/api/{{api_version}}/files
Accept-Language: {{default_language}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="default.jpg"
Content-Type: image/svg+xml

< ./../../resources/files/default.jpg
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });

    if (201 === response.status) {
        client.global.set("file_id", response.body.id);
    }
%}
